### ISSUE TITLE
Tracking issue for the RoadRunner 2.0

### ISSUE THREAD

**Issue by 48d90782** [spiral/roadrunner#368]
In RR 2.0 with the rest features and improvements, we will introduce a new container for plugins based on the graphs with topological sorting.
This is the tracking ticket with the features we plan to implement in RR 2.0. Here is (not a complete) list with features:
## TODO in 2.0:
- [x] New golang plugin container [endure](https://github.com/spiral/endure)
- [x] Loading worker after request in development mode #299 
- [x] Tests for the new plugins ~#384~ ~#385~ ~#386~ ~#415~  ~#363~
- [x] General plugins migrate [~Metrics #387~ , ~RPC~, ~HTTP #389~, ~Resetter #393~ , ~Informer #394~, ~Logger #208~, ~Server~, ~Gzip #404~, ~Static #405~, ~Headers #406~, ~Health #407~, ~Reloader #436~ , ~KV #444~ ]
- [x] Switch to the `spiral/errors` package #382 
- [x] Improve documentation ~#391~, ~#465~
- [x] Comments https://github.com/spiral/roadrunner/issues/395#issuecomment-725966487
- [x] ~Push RR2 to the benchmarkers #445~ 
- [x] Goridge3 integration #446 
- [x] Allowing HTTP and HTTPS server to listen on Unix sockets #412 #422
- [x] Uniform .rr.yaml, use underscore notation #458 
- [x] CLI #430 
- [x] CherryPick #442 
- [x] Stabilization ~#479~ ~#480~ ~#481~ ~#478~ ~#484~
- [x] Update docker build #488 
- [x] Temporal #482
- [x] Add composer.json to repository #492
- [x] stderr on the Windows #467

## Later 2.0 releases
Likely these plugins won't be in the RR 2.0.0 but arrive in later releases (1-2 month from the 2.0)
- [ ] Lazy workers and adaptive scaling #131 #97
- [ ] Broadcast and broadcast-ws plugins migrate #513 
- [ ] Replace `net.http` (HTTP plugin) with `fasthttp` in separate plugin #334 
- [ ] New gRPC plugin #402 
- [ ] Extend HTTP configuration options #457 
- [ ] New Jobs plugin #403 
- [ ] Core dumps (Linux). how-to Readme
- [ ] Linux (`apt`, `pacman`), Windows (`winget`) and MacOS (`brew`) package managers support  #397 
- [ ] send Etag header in Response for static files #16 
- [ ] Check if supported properly #435 
- [ ] Google Cloud SQL inside RR #443 
- [ ] HTTP metrics #489 
- [ ] Add structural and user-friendly log options #490 

## Discuss
- [ ] Hot reload plugins #369
- [x] ~Middlewares by transport #413~
---
### Feel free to discuss here any features that you're really sure should be in the release.

**Comment by bjuri** [comment]
1. Add this feature [Loading worker after request in development mode](https://github.com/spiral/roadrunner/issues/299)
2. Add global reset command that just run resets all available modules in roadrunner instance, e.g.:
We have http, grpc and jobs modules, we need to reset all modules.
Currently we have to run 3 times: `spiral <module>:reset`
We would like to have an alternative, like: `spiral all:reset` which is reset all 3 modules
Or maybe more flexible one: `spiral reset-modules=http,jobs` which is provide list of modules to reset and cover all modules like `spiral reset-modules=all`

**Comment by bjuri** [comment]
Another one feature: [[FEATURE REQUEST] Add possibility to use dynamic modules like in nginx, apache, php, etc.](https://github.com/spiral/roadrunner/issues/369)

**Comment by bjuri** [comment]
4. Add roadrunner command to reload RR configs without full stop and start of the entire instance, like in nginx.
Way to handle this also could be borrowed from nginx, e.g. using command: `nginx -s reload`, using signals like `HUP`

**Comment by 48d90782** [comment]
> 1. Another one feature: [[FEATURE REQUEST] Add possibility to use dynamic modules like in nginx, apache, php, etc.](https://github.com/spiral/roadrunner/issues/369)

I quite agree that this is a very cool feature. I'll update the ticket in the Endure

**Comment by wolfy-j** [comment]
Done #299

**Comment by 48d90782** [comment]
This is the tracking ticket for the new RR 2.0 config:
```yaml
  http:
    address: 0.0.0.0:8080
    middleware: ["jwt", "session"] // NEW
    maxRequestSize: 200
    uploads:
      forbid: [ ".php", ".exe", ".bat" ]
    trustedSubnets: [ "10.0.0.0/8", "127.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "::1/128", "fc00::/7", "fe80::/10" ]
    pool:
      numWorkers: 4
      maxJobs:  0
      allocateTimeout: 60
      destroyTimeout:  60

  ssl:
    port:     443
    redirect: true
    cert:     server.crt
    key:      server.key
    rootCa:   root.crt
  fcgi:
    address: tcp://0.0.0.0:6920
  http2:
    enabled: true
    h2c: true
    maxConcurrentStreams: 128
```

**Comment by 48d90782** [comment]
The rest tickets from the `Later 2.0 releases` will be in the separate sprint tracking tickets.
